BMH-111
uc-cdis/gen3sdk-python pull request #140
Opened 2022-07-07 18:56 UTC by tianj7

Jira Ticket: [BMH-111](https://ctds-planx.atlassian.net/browse/BMH-111)

### New Features

- Gen3Auth can now communicate with external WTS instances 
- Gen3Auth can obtain access token to target Gen3 commons based on user specified endpoint parameter
- Gen3Auth will set endpoint correctly based on user input 

### Breaking Changes

### Bug Fixes

### Improvements

### Dependency updates

### Deployment changes

2022-07-08 17:08 UTC, Avantol13 requested changes

2022-07-08 17:08 UTC, Avantol13 commented on gen3/auth.py
> +                cache_file = token_cache_file(
I'm not sure I understand what this token_cache_function is doing. Why are you passing a boolean expression (foo and bar) ?

2022-07-08 17:08 UTC, Avantol13 commented on gen3/auth.py
> +        try:
```suggestion
        
        try:
```

2022-07-08 17:08 UTC, Avantol13 commented on gen3/auth.py
> +            if (resp and resp.status_code == 200) or (self._external_wts_host == None):
Unless it's vital that the `self._external_wts_host == None` be compared to None, let's just use Python's truthiness. So ```
if (resp and resp.status_code == 200) or not self._external_wts_host:
```

2022-07-08 17:08 UTC, Avantol13 commented on gen3/auth.py
> +            if self._external_wts_host == None:
see above re: None

2022-07-08 17:08 UTC, Avantol13 commented on gen3/auth.py
> +                    "No idp matched with endpoint value provided. Query /wts/external_oidc/ for list of all available idps."
can you just provide the list of all available idps here in the error message?

2022-07-08 17:08 UTC, Avantol13 commented on gen3/auth.py
> +                    "Multiple idps matched with endpoint value provided. Query /wts/external_oidc/ for specific idp names."
see above

2022-07-08 17:08 UTC, Avantol13 commented on tests/conftest.py
> +    # unstable and not supported on OS X, forking is only supported on Unix
```suggestion
    # NOTE: fork is unstable and not technically supported on OS X, forking is only supported on Unix
```

2022-07-08 17:08 UTC, Avantol13 commented on tests/test_auth.py
> +def test_auth_init_with_external_wts():
I think we need more tests than these. We want to test things like passing in an IdP that doesn't exist, what if token and IdP are different/same

2022-07-08 17:49 UTC, tianj7 commented on gen3/auth.py
> +                    raise g
This block is making sure we raise the correct Gen3AuthError raised (cannot obtain token). The except block below is catching all exceptions and raise a value error indicating the refresh file couldn't be loaded. In reality, the refresh token file could be loaded correctly and the fault is actually not being able to obtain an access token from the local/remote wts instance.

2022-07-08 19:12 UTC, Avantol13 commented on gen3/auth.py
> +                    raise g
oh, I see know. Okay, let's maybe add a log here to clarify that's the error that's occuring

2022-07-08 19:23 UTC, Avantol13 commented on gen3/auth.py
> +                cache_file = token_cache_file(
isn't this the function? https://github.com/uc-cdis/gen3sdk-python/blob/19cadb5f8e47b2f8ecff50914a9be04a0a59070f/gen3/auth.py#L91 it looks like the input is just a key to encode. But `_wts_idp` is just a string for the name, it's not a key. 

So are you reusing this same file to cache just the name? it's maybe a little misleading.. perhaps we just need to rename some stuff in the code to make it clean that this is not ONLY a cache file for the key now. 

I also don't know how I feel about the `foo and bar` logic as an argument into the function. The behavior of which is used is understandable but a little too strange at first glance to me.

```
>>> def test(foobar):
...     print(foobar)
... 
>>> test("string" and "anotherstring")
anotherstring
>>> test("string" and None)
None
>>> test(None and "anotherstring")
None
>>> 
```

You could just:
```
if self._refresh_token:
     cache_file = token_cache_file(self._refresh_token.get("api_key", ""))
```
or if you really want a one-liner (which is debatable if it's more readable - I don't think it is) you could do:
```
cache_file = token_cache_file(getattr(self, "_refresh_token", {}).get("api_key", ""))
```

2022-07-08 19:39 UTC, tianj7 commented on gen3/auth.py
> +                cache_file = token_cache_file(
Thanks, that makes sense. For the wts case, think I will use `self._refresh_token.get("api_key", "") + _wts_idp ` as the key which should suffice for this purpose.

2022-07-11 15:52 UTC, tianj7 commented on gen3/auth.py
> +    resp = requests.get(wts_url + "external_oidc/")
Fixed

2022-07-11 15:52 UTC, tianj7 commented on gen3/auth.py
> +                    raise g
Fixed

2022-07-11 15:54 UTC, tianj7 commented on gen3/auth.py
> +                    if (not endpoint == None) and (
the second condition is comparing a ) user supplied endpoint and b) endpoint from the refresh file. If they do NOT agree with each other, then we know we need to use WTS. If they do, then we could just simply load the refresh_file which we have already done. The none reference check has been fixed.

2022-07-11 15:54 UTC, tianj7 commented on gen3/auth.py
> +            if self._external_wts_host == None:
fixed

2022-07-11 15:54 UTC, tianj7 commented on gen3/auth.py
> +        if self._use_wts == True:
fixed.

2022-07-11 15:55 UTC, tianj7 commented on gen3/auth.py
> +        try:
fixed.

2022-07-11 15:56 UTC, tianj7 commented on gen3/auth.py
> +            if (resp and resp.status_code == 200) or (self._external_wts_host == None):
fixed.

2022-07-11 16:30 UTC, tianj7 commented on gen3/auth.py
> +                cache_file = token_cache_file(
code refactored per conversation.

2022-07-11 19:05 UTC, tianj7 commented on gen3/auth.py
> +                    "No idp matched with endpoint value provided. Query /wts/external_oidc/ for list of all available idps."
fixed.

2022-07-11 19:05 UTC, tianj7 commented on gen3/auth.py
> +                    "Multiple idps matched with endpoint value provided. Query /wts/external_oidc/ for specific idp names."
fixed.

2022-07-11 20:30 UTC, tianj7 commented on gen3/auth.py
> +    resp = requests.get(wts_url + "external_oidc/")
the trailing "/" in "/external_oidc/" is required to get the correct json return value.

2022-07-11 20:41 UTC, tianj7 commented on tests/test_auth.py
> +def test_auth_init_with_external_wts():
Added new unit tests

2022-07-12 15:50 UTC, Avantol13 commented on gen3/auth.py
> +        providerList = get_wts_idps(self._wts_namespace, self._external_wts_host)
```suggestion
        provider_list = get_wts_idps(self._wts_namespace, self._external_wts_host)
```

python locally scoped variables should be `lowercase_underscore_separated`

2022-07-12 15:51 UTC, Avantol13 commented on gen3/cli/objects.py
> -    "--force-metadata-columns-even-if-empty",
I think a merge went wrong? This is a new feature that shouldn't be removed

2022-07-12 15:52 UTC, Avantol13 commented on gen3/tools/indexing/index_manifest.py
> -        force_metadata_columns_even_if_empty(bool): force the creation of a metadata column
all of this is the new feature that should still exist, I think a merge went wrong and you got rid of recent commits on master

2022-07-12 15:55 UTC, Avantol13 commented on tests/test_auth.py
> +
docstring

2022-07-12 15:56 UTC, Avantol13 commented on tests/test_auth.py
> +        print(e)
why are we catching and printing an exception in the unit test?

2022-07-12 15:56 UTC, Avantol13 commented on tests/test_auth.py
> +    os.remove("testCred.json")
is this safely done even if that file doesn't exist?

2022-07-12 15:56 UTC, Avantol13 commented on tests/test_auth.py
> +                assert str(e).startswith(
same comment as above, we should just test for the ValueError, not the content of the message

2022-07-12 15:58 UTC, Avantol13 commented on tests/test_auth.py
> +                assert str(e).startswith(
it will make the tests a little too brittle for my liking

2022-07-12 15:59 UTC, Avantol13 commented on tests/test_manifests.py
> -def test_index_manifest_additional_metadata_force(
this looks like another part of the bad merge, we don't want to remove this

2022-07-12 20:46 UTC, Avantol13 commented on tests/test_manifests.py
> -
seems unnecessary

2022-07-12 21:09 UTC, Avantol13 approved these changes

2022-07-12 21:14 UTC, merged