BMH-163
uc-cdis/gen3sdk-python pull request #144
Opened 2022-07-15 20:06 UTC by tianj7

Jira Ticket: BMH-163
### Improvements
- add no_throw flag to metadata.get()
- improve warning message for cache file write error

2022-07-15 21:10 UTC, mfshao requested changes

2022-07-15 21:10 UTC, mfshao commented on gen3/tools/download/drs_download.py
> +                    mds_entry = self.metadata.get(entry.object_id, no_throw=True)
I don't understand why we need to do this

The temporary mitigation solution is to use `--no-unpack-packages` to bypass this check
The correct fix for this should be: if Gen3SDK is being used in a Gen3 ecosystem workspace, it should figure out which child MDS to query and send the query to the correct commons to get metadata back

Disabling throwing exception from here makes no sense, and it is actually going to mute errors that should have been thrown out if SDK is being used in a standlone envirnmont, for example, by users who is going to use SDK on their local computers

2022-07-18 14:40 UTC, tianj7 commented on gen3/tools/download/drs_download.py
> +                    mds_entry = self.metadata.get(entry.object_id, no_throw=True)
To my understand, the objects in the BRH notebook user is trying to pull are zip files and not data packages. They do not need to be unpacked but drs download will by default attempt to contact mds. There is no associated metadata for these objects so 404 warnings will appear, which is confusing to users. The relevant conversation thread is here: https://cdis.slack.com/archives/C03A7E397E2/p1657216612023659

2022-07-18 15:45 UTC, Avantol13 commented on gen3/metadata.py
> +    def get(self, guid, no_throw=False, **kwargs):
I don't like the naming here. We need to be super explicit about what we're ignoring/forcing in this variable name and subsequent docstring

2022-07-18 15:51 UTC, Avantol13 commented on gen3/tools/download/drs_download.py
> +                    mds_entry = self.metadata.get(entry.object_id, no_throw=True)
I don't have all the context, but I agree that ignoring errors from the MDS call is dangerous. This also ignores legitimate errors that might occur. Can this higher-level function just catch the MDS 404 error and handle that here if you need to? 

The 404 is legitimate in this situation. Is the whole thing failing because of those errors or is it just that the log file ends up with 404s? If it's the latter, I'd argue we add some clarity in a future log message, not suppress the HTTP responses being logged. Like at the end, if you know there was an object with no MDS records, you can print a log at the end like: `Files successfully downloaded. Some files did not have associated metadata (see errors in the logs for more details). This did **not** affect the download of the actual files and may or may not be of concern.` or something

2022-07-18 17:03 UTC, mfshao reviewed
changes are being discussed

2022-07-18 21:06 UTC, Avantol13 approved these changes

2022-07-20 19:31 UTC, Avantol13 approved these changes

2022-07-20 19:42 UTC, merged