Add client credentials support to Gen3Auth
uc-cdis/gen3sdk-python pull request #167
Opened 2022-12-02 22:24 UTC by paulineribeyre

### New Features
- Add client credentials support to Gen3Auth: `Gen3Auth(client_credentials=("client ID", "client secret"))`

2022-12-13 21:13 UTC, Avantol13 requested changes

2022-12-14 16:42 UTC, paulineribeyre commented on gen3/auth.py
> +            self._client_scopes = client_scopes or "user data openid"
i don't get what you mean, can you explain? i set it here to avoid null or empty values

2022-12-14 18:06 UTC, paulineribeyre commented on gen3/auth.py
> +            self._client_scopes = client_scopes or "user data openid"
if i change this, i also have to refactor the logic for the error when `client_scopes` is specified and `client_credentials` is not, since `client_scopes` is never null. I would rather keep this if that's fine

2022-12-14 18:09 UTC, Avantol13 commented on gen3/auth.py
> +            self._client_scopes = client_scopes or "user data openid"
totally fine, yeah I missed that case. :+1:

2022-12-14 18:31 UTC, Avantol13 approved these changes

2022-12-14 19:11 UTC, merged