BRH-314
uc-cdis/gen3sdk-python pull request #180
Opened 2023-03-27 20:13 UTC by tianj7

Jira Ticket: https://ctds-planx.atlassian.net/browse/BRH-314

### Improvements
Add confirmation message for successful DRS downloads

2023-03-29 16:19 UTC, Avantol13 requested changes

2023-03-29 16:19 UTC, Avantol13 commented on gen3/tools/download/drs_download.py
> +logger = get_logger("drs-pull", log_level="info")
We shouldn't manually set the log_level here. It should be configurable by the client what log level they want to see. This was recently added to the SDK `gen3 -v` and `gen3 -vv`. You should try removing the log_level entirely from here and update the command call to specify the verbosity. If you want info messages, use `gen3 -v ...`

from `gen3 --help`:
```
  -v                 verbose logs show INFO, WARNING & ERROR logs
  -vv                very verbose logs show DEGUG, INFO, WARNING & ERROR logs

```

2023-03-31 21:46 UTC, tianj7 commented on gen3/tools/download/drs_download.py
> +logger = get_logger("drs-pull", log_level="info")
Code modified to use default flags and use click.echo to display download success/error messages

2023-04-03 15:44 UTC, Avantol13 commented on gen3/cli/drs_pull.py
> +        if res[drs_object_id].status != "downloaded":
```suggestion
        if drs_object_id in res and res[drs_object_id].status != "downloaded":
```

2023-04-03 15:46 UTC, Avantol13 commented on gen3/cli/drs_pull.py
> +            click.echo(f"Object {drs_object_id} have not been successfully downloaded.")
```suggestion
            click.echo(f"Object {drs_object_id} has failed to downloaded.")
```

remove "success" b/c at a glance someone might miss the "not" and think it worked

2023-04-03 15:46 UTC, Avantol13 commented on gen3/cli/drs_pull.py
> +            click.echo(f"Object {drs_object_id} have been successfully downloaded.")
Do we need it to echo for every successful download or just if one fails? Seems like this might be too much output on the command line

2023-04-03 15:47 UTC, Avantol13 commented on gen3/tools/download/drs_download.py
> +                logger.info(
maybe debug instead of info. This could get pretty noisy

2023-04-03 15:47 UTC, Avantol13 commented on gen3/tools/download/drs_download.py
> +                completed[entry.object_id].status = "error"
why a log above for success but not for failure here?

2023-04-03 15:48 UTC, Avantol13 requested changes
see comments

2023-04-03 16:22 UTC, tianj7 commented on gen3/cli/drs_pull.py
> +            click.echo(f"Object {drs_object_id} have been successfully downloaded.")
rewrote this to just show individual failures only and a final success/failure message.

2023-04-03 16:22 UTC, Avantol13 approved these changes

2023-04-03 16:23 UTC, merged