initial discovery objects implementation
uc-cdis/gen3sdk-python pull request #188
Opened 2023-06-20 08:55 UTC by SpencerAxelrod

Jira Ticket: [PXP-10961](https://ctds-planx.atlassian.net/browse/PXP-10961)

### New Features
discovery objects READ, PUBLISH, and DELETE

### Breaking Changes

### Bug Fixes

### Improvements

### Dependency updates

### Deployment changes

[PXP-10961]: https://ctds-planx.atlassian.net/browse/PXP-10961?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-06-20 20:55 UTC, Avantol13 requested changes

2023-06-20 20:55 UTC, Avantol13 commented on gen3/cli/discovery.py
> +    Output can be piped into another command
Probably want something more descriptive here. What's the output, maybe an example, then describe idea that it can be piped

2023-06-20 20:55 UTC, Avantol13 commented on gen3/cli/discovery.py
> +    "dataset_guids",
Can you have `help` for an argument here? If so you should add it

2023-06-20 20:55 UTC, Avantol13 commented on gen3/cli/discovery.py
> +    Output a file that can be easily hand-modified and then published
```suggestion
    Output a TSV with required columns for `publish`. Will NOT contain any actual existing values for datasets or objects. If you want the full output of what's in the commons, don't supply this flag.
```

2023-06-20 20:55 UTC, Avantol13 commented on gen3/cli/discovery.py
> +        click.echo(output_file)
I assume this isn't implemented yet

2023-06-20 20:55 UTC, Avantol13 commented on gen3/cli/discovery.py
> +    help="Takes a TSV as input. If dataset_guid already exists, update, if it doesn’t already exist, create it"
Should include a reference to use `read --template` to get a TSV in the expected format

2023-06-27 14:23 UTC, SpencerAxelrod commented on gen3/cli/discovery.py
> +        click.echo(output_file)
This is just to output the tsv filename. If --only-object-guids is on, then there is no file, so it does not output a filename

2023-06-29 16:12 UTC, SpencerAxelrod commented on gen3/cli/discovery.py
> +    "dataset_guids",
No --help for args it seems, so added more description to the overall command help

2023-06-29 16:25 UTC, Avantol13 requested changes

2023-06-29 16:25 UTC, Avantol13 commented on gen3/tools/metadata/discovery_objects.py
> +                            print(obj["guid"])
I'm not sure the ultimate difference, but I think `click.echo` is likely the better choice here to output to the command line

2023-06-29 16:25 UTC, Avantol13 commented on gen3/tools/metadata/discovery_objects.py
> +            object_fields = {"dataset_guid", "guid", "display_name"}
These are somewhat "magic numbers", I'd prefer a named constant (maybe even a global at the top)

2023-06-29 16:25 UTC, Avantol13 commented on gen3/tools/metadata/discovery_objects.py
> +    Publish discovery objects from a tsv file
```suggestion
    Publish discovery objects from a TSV file
```

2023-06-29 16:25 UTC, Avantol13 commented on gen3/tools/metadata/discovery_objects.py
> +            f"Unsupported file type supplied {metadata_filename}! Only TSV are allowed."
we can actually pretty easily support CSV or TSV but I think it's fine to only allow one

2023-06-29 16:25 UTC, Avantol13 commented on gen3/tools/metadata/discovery_objects.py
> +            required_fields = ["dataset_guid", "guid", "display_name"]
if we had global constants defining these (see above) you can use them here

2023-06-29 16:25 UTC, Avantol13 commented on gen3/tools/metadata/discovery_objects.py
> +                logging.error(f"Missing required field/s {missing_fields}.")
```suggestion
                logging.error(f"Missing required field(s) {missing_fields}.")
```

2023-06-29 16:25 UTC, Avantol13 commented on gen3/tools/metadata/discovery_objects.py
> +                raise ValueError(f"Required field/s missing: {missing_fields}")
```suggestion
                raise ValueError(f"Required field(s) missing: {missing_fields}")
```

2023-06-29 16:25 UTC, Avantol13 commented on gen3/tools/metadata/discovery_objects.py
> +        if arg[-4:] == ".tsv":
```suggestion
        if arg[-4:].lower() == ".tsv":
```

2023-06-29 16:25 UTC, Avantol13 commented on gen3/tools/metadata/discovery_objects.py
> +        else:
I don't really like that this is determined by a variable that could have 2 different meanings. Can we distinguish between file and GUID before this function call?

2023-06-29 16:25 UTC, Avantol13 commented on gen3/tools/metadata/discovery_objects.py
> +        else:
Click should have a way to specify a file. Maybe both are optional args `--file` or `--guids` and if you don't supply either, Click prompts you to specify a file.

2023-06-29 16:25 UTC, Avantol13 commented on gen3/tools/metadata/discovery_objects.py
> +                    guid = row["guid"]
are we validating the file format before this? if not, these dict accesses could fail. I'd propose we have some minimal validation function to ensure the expected columns are there

2023-06-29 16:25 UTC, Avantol13 commented on tests/test_discovery_objects.py
> +        # output with no dataset_args should return all objects from all datasets
this should be a separate unit test. Each test should be testing an isolated functionality. If you're calling the thing you're "testing" more than once, you should make a new test or parameterize the input using pytest to have it automatically run separate tests for different inputs

2023-06-29 16:25 UTC, Avantol13 commented on tests/test_discovery_objects.py
> +            output_discovery_objects(
same comment as above, new test

2023-06-29 16:25 UTC, Avantol13 commented on tests/test_discovery_objects.py
> +    # JSON output tests
same comment as above, new test

2023-07-06 16:56 UTC, Avantol13 requested changes

2023-07-06 16:56 UTC, Avantol13 commented on gen3/cli/discovery.py
> +    auth = ctx.obj["auth_factory"].get()
docstring

2023-07-06 16:56 UTC, Avantol13 commented on gen3/cli/discovery.py
> +@discovery.group()
can you add a section to the `docs/howto/discoveryMetadataTools.md` for this new functionality? We've been trying to add some docs and example scripts as we add new functionality. You can borrow language from the feature doc.

Maybe a new section called `Publish Discovery Metadata Objects from File`, and model it after existing docs in there and show

2023-07-10 18:15 UTC, Avantol13 commented on gen3/cli/discovery.py
> +            "It appears like you are attempting to publish from a discovery objects file. Are you sure you want proceed with publishing?",
```suggestion
            "WARNING! It appears like you are attempting to publish discovery **objects** (based on the file provided) but you are attempting to use the non-object, dataset-level command `gen3 discovery publish`. Perhaps you meant to use `gen3 discovery objects publish`. Are you sure you want proceed with publishing the dataset-level discovery metadata using the object file?",
```

2023-07-10 20:14 UTC, Avantol13 approved these changes

2023-07-10 20:16 UTC, merged