merge_manifests fix for rows with no guid
uc-cdis/gen3sdk-python pull request #196
Opened 2023-08-28 14:29 UTC by SpencerAxelrod

Jira Ticket: [PXP-xxxx](https://ctds-planx.atlassian.net/browse/PXP-xxxx)
- [ ] Remove this line if you've changed the title to (PXP-xxxx): <title>

### New Features

### Breaking Changes

### Bug Fixes
merge_manifests fix for rows with no guid

### Improvements

### Dependency updates

### Deployment changes

2023-08-28 14:51 UTC, SpencerAxelrod commented on gen3/tools/indexing/merge_manifests.py
> +    records_with_no_guid = []
move `records_with_no_guid` initialization, as well as the `for record in records_with_no_guid` loop to outside the `for manifest in files:` loop. This would process the records with no guid after _all_ manifests rows have been initially processed.

2023-08-28 14:51 UTC, SpencerAxelrod commented on gen3/tools/indexing/merge_manifests.py
> +    for record in records_with_no_guid:
see above comment re: moving this loop outside of `for manifest in files` loop

2023-12-06 18:11 UTC, k-burt-uch commented
Please write a regression test. 

Also the bug fix section in your PR template is very thorough but unfortunately our release note automation won't be able to parse it properly due to the multiple line breaks. 

I think something more succinct like 

"Fixes issue with merge_bucket_manifests where the order of input manifests would inconsistent (and incorrect) merge behavior."

2023-12-06 18:13 UTC, k-burt-uch requested changes
Please write a regression test.

Also the bug fix section in your PR template is very thorough but unfortunately our release note automation won't be able to parse it properly due to the multiple line breaks.

I think something more succinct like

"Fixes issue with merge_bucket_manifests where the order of input manifests would inconsistent (and incorrect) merge behavior."

2023-12-06 18:20 UTC, Avantol13 commented
> Also the bug fix section in your PR template is very thorough but unfortunately our release note automation won't be able to parse it properly due to the multiple line breaks.
> 
> I think something more succinct like
> 
> "Fixes issue with merge_bucket_manifests where the order of input manifests would inconsistent (and incorrect) merge behavior."
You can leave the detailed description above the headings for posterity if someone looks at this PR again. But that's right, the bullet under the heading should be succinct, like one sentence

2023-12-06 22:21 UTC, k-burt-uch approved these changes
Unit test provided that verifies the order of manifests does not matter when a guid is not provided in one manifest and that the end result is the same. Approved.

2023-12-06 22:37 UTC, merged