fix(doi): correct metadata return to use original phsids, improve doc…
uc-cdis/gen3sdk-python pull request #215
Opened 2024-03-13 19:14 UTC by Avantol13

…s / debugging

### New Features

### Breaking Changes

### Bug Fixes
- correct metadata return to use original phsids for DOI retrieval from dbGaP API

### Improvements
- allow overriding access token in auth function
- fix wrong argument name in documentation

### Dependency updates

### Deployment changes

2024-03-26 13:02 UTC, k-burt-uch requested changes
Only necessary change for approval is clearing up the wording in the access_token docs. Everything else is minor and opinionated code quality and not a blocker for merge.

2024-03-26 13:02 UTC, k-burt-uch commented on gen3/doi.py
> +            self.resolver = resolver
actually could we get rid of use_prod entirely and have the default resolver be the test resolver? We have an enum that denotes the test vs prod resolver so passing in the prod one is simple for the use_prod=True case.

2024-03-26 13:02 UTC, k-burt-uch commented on gen3/doi.py
> +            self.resolver = resolver
better yet - could we make the resolver a constructor parameter?

2024-03-26 15:09 UTC, Avantol13 commented on gen3/doi.py
> +            self.resolver = resolver
I need to give this some more thought b/c `use_prod` has multiple uses and I mirrored the logic from the other use for consistency. This arg also determines the API used in DataCite (and there are enums in use there as well https://github.com/uc-cdis/gen3sdk-python/blob/6da740a343ad239b170a446301ceaa7a2fbff09e/gen3/doi.py#L107-L110 ). This is  the same pattern except instead of `api` it's a `resolver`. So if I changed things I would want to change both places, only require `api` and `resolver`, default to test.

I think I'm leaning towards leaving it but I'm open to push back. The benefit of the single boolean is that at the higher level function https://github.com/uc-cdis/gen3sdk-python/blob/6da740a343ad239b170a446301ceaa7a2fbff09e/gen3/discovery_dois.py#L134 you can just have 1 param that gets directly sent into the lower level DataCite and the DOI object itself.

I guess that high level function could still have that bool but update to send in the right API/resolver too. Maybe I'm being lazy. What do you think?

2024-04-10 15:37 UTC, AlbertSnows reviewed
no glaring issue from what I've seen, but it's a bit hard to review the doc/html files. I also lack the full context of the other bits so there may remain opaque gotchas.

2024-04-10 15:37 UTC, AlbertSnows commented on gen3/doi.py
> +            self.resolver = resolver
Is use_prod static for this class? If so I'd be wondering if there's a better alternative. I may have to think about it more but my initial impression would be to have an enum mapper or something. (prod, staging, etc, as needed)

2024-04-10 15:39 UTC, AlbertSnows commented
> no glaring issue from what I've seen, but it's a bit hard to review the doc/html files. I also lack the full context of the other bits so there may remain opaque gotchas.

oh also if I have time I may look closer at all the params being added. In general there's no issue, but I vaguely recall there being a way to design functions and classes to not have a params waterfalll.

2024-04-10 15:40 UTC, Avantol13 commented on gen3/doi.py
> +            self.resolver = resolver
The value of it can't necessarily be static, b/c you might want to write code that first tests DOIs in the test site and then flips it to prod afters some automatic QA.

But there are class-level enums already, that's what `DataCite.PRODUCTION_URL` and `DataCite.TEST_URL` are

2024-04-10 15:41 UTC, Avantol13 commented
> no glaring issue from what I've seen, but it's a bit hard to review the doc/html files. I also lack the full context of the other bits so there may remain opaque gotchas.

You can always ignore files in the docs folder b/c they're auto-generated

2024-04-10 16:00 UTC, k-burt-uch approved these changes

2024-04-10 16:00 UTC, k-burt-uch commented on gen3/external/nih/dbgap_study_registration.py
> +            parent_simplified = standardized_phsid_parts["phsid"]
thanks for catching this.

2024-04-15 20:04 UTC, merged