DCF-1735: Add user security module for internal use
uc-cdis/gen3sdk-python pull request #219
Opened 2024-05-08 18:53 UTC by jacob50231

### New Features
* Added function that scans user yaml files for security concerns

2024-05-21 15:09 UTC, BedfordWest requested changes
Great work! Just the one change we discussed during our touchpoint.

2024-05-21 15:09 UTC, BedfordWest commented on gen3/tools/indexing/user_security.py
> +        while continue_input.lower() not in ["y", "n"]:
As discussed earlier, let's set a timeout for this and skip it entirely if there are no instances of the phsid found.

2024-06-03 14:56 UTC, BedfordWest requested changes
Overall looks good! Just one request about the timeout duration.

2024-06-03 14:56 UTC, BedfordWest commented on gen3/tools/indexing/user_security.py
> +        timeout = 5
5 seconds feels a bit short to me. Can we make it a bit longer? Maybe 15s?

2024-06-03 15:27 UTC, BedfordWest approved these changes

2024-06-03 15:27 UTC, merged

2024-06-06 21:25 UTC, paulineribeyre commented on gen3/tools/indexing/user_security.py
> +            if policies[i]["id"] == "open_data_reader":
@BedfordWest @jacob50231 I'm a bit late but since the Gen3 SDK is widely used externally, i think the docstring should document the limitations and assumptions we make in this script, ie that "public access" == "open_data_reader" policy. That's not necessarily true:
- What do we mean by "public"? The "anonymous_policies" group or "all_users_policies" group, or both?
- Those groups can include any policies we want, not just "open_data_reader".
- Using the name "open_data_reader" is a convention that isn't enforced and we use a different name sometimes, even internally.

Example: https://github.com/uc-cdis/commons-users/blob/bc1c4f4/users/midrc/user.yaml#L12-L23

If this is meant to be usable by others, we should update the script (check all policies in the 2 groups). If not, we should at least document the assumptions (or just keep this internal script in a different repo).

From a quick read, other things to document:
- The hardcoded `owner = "uc-cdis"` (since the `path` and `repo` are already parameters, why not this one too?)
- What a "phsid" is (external folks may not know what that is, "resource_name" would be more generic)

Also quick note that unit tests would have been nice, also because the sdk is an external tool

2024-06-06 21:58 UTC, paulineribeyre commented on gen3/tools/indexing/user_security.py
> +            if policies[i]["id"] == "open_data_reader":
Actually this would be a great addition to the gen3users tool!

2024-06-18 15:59 UTC, paulineribeyre commented on gen3/tools/indexing/user_security.py
> +            if policies[i]["id"] == "open_data_reader":
https://ctds-planx.atlassian.net/browse/DCF-1771