Adding post_indexing_validation module
uc-cdis/gen3sdk-python pull request #246
Opened 2024-12-17 22:27 UTC by jacob50231

Link to JIRA ticket if there is one: 

### New Features
Adds a module for post-indexing validation

2024-12-19 17:34 UTC, BedfordWest requested changes
A few thoughts/requests. I don't necessarily think all of these need to be addressed - we can maybe chat about it when we have a free cycle or eng workshop.

2024-12-19 17:34 UTC, BedfordWest commented on gen3/tools/indexing/post_indexing_validation.py
> +            response_status = 200
This is a little strange to me - is there a reason we're manually setting the status code instead of logging what we actually got?

2024-12-19 17:34 UTC, BedfordWest commented on gen3/tools/indexing/post_indexing_validation.py
> +        self.download_status = download_success
Shouldn't this line be inside the if block? I imagine we wouldn't want to set download_status to download_success if we weren't inside that block, right?

2024-12-19 17:34 UTC, BedfordWest commented on gen3/tools/indexing/post_indexing_validation.py
> +class Records:
Having a "Record" class and "Records" class feels a bit like an anti-pattern to me. It might just be a naming issue, though. Docstrings for the classes explaining their intent might be helpful. If this class is meant more as a utility class to parse input into multiple records (which I think is the case after scanning over it a bit more), a more appropriate name/noun might be something like "RecordCreator" or "RecordParser".

2024-12-19 17:34 UTC, BedfordWest commented on gen3/tools/indexing/post_indexing_validation.py
> +        if manifest[-3:] == "tsv":
Might want to validate the length of the manifest before doing this just in case it's empty or some such and then throw a more helpful error rather than the default invalid index you'd get.

2024-12-19 17:34 UTC, BedfordWest commented on gen3/tools/indexing/post_indexing_validation.py
> +                            if "://" not in url:
Is there a reason we continue here rather than throwing an error? This would be an invalid url format, no?

2024-12-19 17:34 UTC, BedfordWest commented on gen3/tools/indexing/post_indexing_validation.py
> +                                if key not in self.record_dict or (
The logic is getting a little funky here. It may be accurate, but a comment or docstring for the method might be useful to make it a little clearer. Possibly even worth splitting this out a little given how deeply nested it is. Maybe worth separating out url parsing for this purpose into its own utility? Just some thoughts.

2024-12-19 17:34 UTC, BedfordWest commented on gen3/tools/indexing/post_indexing_validation.py
> +                    logger.warning(f"No url parsed for record {guid}")
This feels like it might be more appropriate as an error, no? If we want to ensure everything gets validated and we don't exit early, we could store a list of anything that errored out and then throw an error at the end and provide the list.

2024-12-19 17:34 UTC, BedfordWest commented on gen3/tools/indexing/post_indexing_validation.py
> +        self.download_results = download_results
is there a reason we don't just use self.download_results from the start?

2024-12-19 18:19 UTC, jacob50231 commented on gen3/tools/indexing/post_indexing_validation.py
> +            response_status = 200
So instead of returning a requests.Response object Gen3File.get_presigned_url returns the json from that file which does not contain the status code. I'm only able to obtain a status code directly when raise_for_status_and_print_error raises an HTTPError from within get_presigned_url, but since that raises an error any time the status is 200, if it doesn't raise one I know the status is 200 so I set it manually. (I know it feels hacky and I hated doing it this way but it was the only way to do it without also updating the get_presigned_url function which would almost certainly cause breaking changes somewhere)

2024-12-19 18:26 UTC, jacob50231 commented on gen3/tools/indexing/post_indexing_validation.py
> +        self.download_status = download_success
This was a bad name for this variable. I'm updating the script to not use the variable at all and instead directly change self.download_status

2024-12-19 18:27 UTC, jacob50231 commented on gen3/tools/indexing/post_indexing_validation.py
> +class Records:
Yeah it's the latter. Renaming the class to make this more clear.

2024-12-19 18:32 UTC, jacob50231 commented on gen3/tools/indexing/post_indexing_validation.py
> +        self.download_results = download_results
This should've been changed earlier when I added download_results as a class attribute. Good catch!

2024-12-19 18:32 UTC, jacob50231 commented on gen3/tools/indexing/post_indexing_validation.py
> +        if manifest[-3:] == "tsv":
Will update the validation more here good catch!

2024-12-19 21:43 UTC, jacob50231 commented on gen3/tools/indexing/post_indexing_validation.py
> +                            if "://" not in url:
Changed to throw an error

2024-12-19 21:44 UTC, jacob50231 commented on gen3/tools/indexing/post_indexing_validation.py
> +                                if key not in self.record_dict or (
Set some comments to make it clearer. If you still want me to separate this out I can.

2024-12-19 21:44 UTC, jacob50231 commented on gen3/tools/indexing/post_indexing_validation.py
> +                    logger.warning(f"No url parsed for record {guid}")
Updated

2024-12-23 16:07 UTC, BedfordWest commented on gen3/tools/indexing/post_indexing_validation.py
> +            response_status = 200
Hmmmm. I think this is OK for now, but not ideal. For future reference, I'd probably just generalize the variable to something like "status_ok" as a bool and then in the log state we got a successful response. It might be the case that this always returns 200 for success now, but there are a bunch of types of successful HTTP responses and it just feels a bit too manual to me! 

But I think this is OK for now and no need to change. Thanks!

2024-12-23 19:20 UTC, merged