fix(add-bearer-token-header) add authorization header for Bearer token
uc-cdis/gen3sdk-python pull request #88
Opened 2021-04-24 05:59 UTC by plooploops

Update Submission to include Authorization Header for Bearer Token (for submit_record).

2021-04-26 20:01 UTC, Avantol13 requested changes
Hello! Thanks for the contribution, excited to work with you on this.

There should have been a pull request template to fill out, do you know if that showed up when you initially created the PR? Either way, can you change your description and follow this template:

```
<!--
Make sure to follow the DEV guidelines (https://gen3.org/resources/developer/dev-introduction/) before asking for review.

- Describe what this pull request does.
- Add short descriptive bullet points for each section if relevant. Keep in mind that they will be parsed automatically to generate official release notes.
- Test manually.
- Maintain or increase the test coverage (if relevant).
- Update the documentation, or justify if not needed.

-->

### New Features


### Breaking Changes


### Bug Fixes


### Improvements


### Dependency updates


### Deployment changes
<!-- This section should only contain important things devops should know when updating service versions. -->

```

2021-04-27 05:38 UTC, plooploops commented on gen3/tools/indexing/index_manifest.py
> +    if "http://localhost" in commons_url and include_service_location:
This was breaking in the unit tests under [test_manifests.py](https://github.com/uc-cdis/gen3sdk-python/blob/master/tests/test_manifests.py#L387)

For example, if `include_service_location` is set to `True`, the unit test would include the following extra /index in the test:

Detail 404 Client Error: no record found for url: http://localhost:8001/index/index/

2021-04-27 05:41 UTC, plooploops commented on README.md
> +## Local Development
Sounds good, will move these over.

2021-04-27 05:56 UTC, plooploops commented on gen3/submission.py
> -        output = requests.put(api_url, auth=self._auth_provider, json=json)
In using the existing version, it looks like we get the following from using a `submit_record` call:

```bash
  File "/sheepdog/sheepdog/blueprint/routes/views/__init__.py", line 59, in get_programs
    auth.validate_request(aud={"openid"}, purpose=None)
  File "/usr/local/lib/python3.6/site-packages/authutils/token/validate.py", line 236, in validate_request
    raise JWTError("no authorization header provided")
authutils.errors.JWTError: [401] - Authentication Error: no authorization header provided
```

However, in trying to replicate the 401's, the error doesn't occur with Sheepdog every time.

In looking into the Auth class, it looks like there's a couple of spots that may be interesting:
* [refreshing a token](https://github.com/uc-cdis/gen3sdk-python/blob/master/gen3/auth.py#L273)
* [getting an access token](https://github.com/uc-cdis/gen3sdk-python/blob/master/gen3/auth.py#L301)

2021-04-27 07:37 UTC, plooploops commented on tests/test_submission.py
> +        assert rec
Opted for checking for an expected response.

2021-04-28 07:04 UTC, plooploops commented on gen3/submission.py
> -        output = requests.put(api_url, auth=self._auth_provider, json=json)
Made an update to include retry logic around writing to files for `refresh_token`.

Looks like the calls should include the header; this could also be the case of using an older version of the lib.

2021-04-29 18:39 UTC, Avantol13 requested changes

2021-04-29 18:39 UTC, Avantol13 commented on gen3/tools/indexing/index_manifest.py
> +    if "http://localhost" in commons_url and include_service_location:
hmm, so I'd rather keep this similar to the link I supplied where the variable is not a boolean, but the actual string path of the service relative to the domain. These won't change often, but it's probably better to leave that option open instead of hard-coding `/index` without a way to change it

2021-04-29 18:39 UTC, Avantol13 commented on tests/test_auth.py
> +    with patch("gen3.auth.get_access_token_with_key") as mock_access_token:
We're not super consistent about this, but I'd prefer that each test have a docstring with a quick sentence about what it's testing. """Make sure that access token ends up in header when refresh is called""" or something like that. same for other tests

2021-04-29 18:39 UTC, Avantol13 commented on gen3/auth.py
> +        retry_total = 5
we actually already have a backoff library with configurable settings I'd rather reuse than implement custom retry logic (example: https://github.com/uc-cdis/gen3sdk-python/blob/feat/merge-refactor/gen3/jobs.py#L110) using https://github.com/litl/backoff. You'll have to change the logic a bit because it retries on an Exception, so instead of _write_to_file being a boolean you could just raise exceptions and the backoff library/cfg will retry the whole function if you decorate it

2021-04-30 01:46 UTC, plooploops commented on tests/test_auth.py
> +    with patch("gen3.auth.get_access_token_with_key") as mock_access_token:
Included in the added tests.

2021-04-30 01:46 UTC, plooploops commented on docs/howto/devTest.md
> +python3 -m venv py38
Updated based on comments.

2021-04-30 01:47 UTC, plooploops commented on gen3/auth.py
> +        retry_total = 5
Included using the backoff library.

2021-04-30 01:47 UTC, plooploops commented on gen3/tools/indexing/index_manifest.py
> +    if "http://localhost" in commons_url and include_service_location:
Updated logic.

2021-05-03 19:46 UTC, Avantol13 commented on gen3/tools/indexing/index_manifest.py
> +    print(commons_url)
```suggestion
```

2021-05-04 00:18 UTC, plooploops commented on gen3/tools/indexing/index_manifest.py
> +    print(commons_url)
Updated!

2021-05-04 21:11 UTC, plooploops commented on docs/howto/devTest.md
> +You can also set up credentials to submit metadata to your data commons.  This assumes that you can get API access by downloading your [credentials.json](https://gen3.org/resources/user/using-api/#cr
Sounds good, updated!

2021-05-05 14:40 UTC, Avantol13 approved these changes

2021-05-05 15:05 UTC, xritter1 commented
Hello @plooploops, could you take a look at the output of the Wool test before we can merge this PR? Thanks!

---

`Black output:
--- gen3/auth.py
+++ blackened
@@ -255,11 +255,11 @@
         _response.request = newreq
 
         return _response
 
     def refresh_access_token(self):
-        """ Get a new access token """
+        """Get a new access token"""
         if self._use_wts:
             self._access_token = get_access_token_from_wts(
                 self._wts_namespace, self._wts_idp
             )
         else:
@@ -296,11 +296,11 @@
             logging.warning("failed to write token cache file: " + cache_file)
             logging.warning(str(e))
             raise e
 
     def get_access_token(self):
-        """ Get the access token - auto refresh if within 5 minutes of expiration """
+        """Get the access token - auto refresh if within 5 minutes of expiration"""
         if not self._access_token:
             cache_file = token_cache_file(
                 self._refresh_token and self._refresh_token["api_key"] or self._wts_idp
             )
             if os.path.isfile(cache_file):


{'message': 'Resource not accessible by integration', 'documentation_url': 'https://docs.github.com/rest/reference/issues#create-an-issue-comment'}`

2021-05-06 16:32 UTC, merged

2021-05-06 16:35 UTC, plooploops commented
Thanks @Avantol13 and @xritter1!